import Head from 'next/head'

export default function Home() {


  function handleSignInClick() {
    window.location.href = '/signin';
  }

  function handleSignUpClick() {
    window.location.href = '/signup';
  }



  return (
    <>
      <Head>
        <title>CollabroMate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div class="flex flex-col space-y-4 items-center">
        <h1 class="text-4xl font-bold">CollabroMate</h1>
        <button class='bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' onClick={handleSignInClick}> Sign In </button>
        <button class='bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' onClick={handleSignUpClick}> Sign Up </button>
      </div>
    </>
  )
}
